version: "3.7"

services:
    app:
        build:
            args:
                user: docker
                uid: 1000
            context: docker/wbpo
        environment:
            XDEBUG_CONFIG: client_host=192.168.0.178
            PHP_IDE_CONFIG: serverName=localhost
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        networks:
            - wbpo-network

    db:
        image: mysql:8.0
        restart: unless-stopped
        ports:
            - 3308:3306
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_USER: ${DB_USERNAME}
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql
        networks:
            - wbpo-network

    nginx:
        image: nginx:alpine
        restart: unless-stopped
        ports:
            - 80:80
        volumes:
            - ./:/var/www
            - ./docker/nginx:/etc/nginx/conf.d/
        networks:
            - wbpo-network

networks:
  wbpo-network:
      driver: bridge
